SuperMarketK/Areas/Admin/Controllers/ContentController.cs
using Model.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.EntityFramework;
using SuperMarketK.Common;
using System.IO;

namespace SuperMarketK.Areas.Admin.Controllers
{
    public class ContentController : BaseController
    {
        // GET: Admin/Content
        public ActionResult Index(string keyword, int page = 1, int pageSize = 10)
        {
            var dao = new ContentDAO();
            var model = dao.ListAllPaging(keyword, page, pageSize);
            var userLogin = (SuperMarketK.Common.UserLogin)Session["USER_SESSION"];
            ViewBag.GroupID = userLogin.GroupID;
            ViewBag.keyword = keyword;
            return View(model);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            return View(new ContentDAO().GetByID(id));
        }

        [HttpGet]
        public ActionResult Create()
        {
            SetViewBag();
            return View();
        }

        [HttpGet]
        public ActionResult Edit(long id)
        {
            var dao = new ContentDAO();
            var content = dao.GetByID(id);

            SetViewBag(content.CategoryID);
            return View(content);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Edit(Content model)
        {
            if (ModelState.IsValid)
            {
                SuperMarketKDbContext db = new SuperMarketKDbContext();
                var content = db.Contents.Find(model.ID);
                content.Detail = model.Detail;
                content.Name = model.Name;
                content.Description = model.Description;
                content.CategoryID = model.CategoryID;
                db.SaveChanges();
            }
            SetViewBag(model.ID);
            return View(model);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Create(Content model, HttpPostedFileBase ImageFile)
        {
            if (ModelState.IsValid)
            {
                string fileName = null;
                if (ImageFile != null && ImageFile.ContentLength > 0)
                {
                    // extract only the fielname
                    fileName = Path.GetFileName(ImageFile.FileName);
                    // store the file inside ~/Assets/client/images folder
                    var path = Path.Combine(Server.MapPath("~/Assets/client/images"), fileName);
                    ImageFile.SaveAs(path);
                }
                var session = (UserLogin)Session[CommonContants.USER_SESSION];
                model.CreatedBy = session.UserName;
                model.Image = "/Assets/client/images/" + fileName;
                new ContentDAO().Create(model);
                return RedirectToAction("Index");
            }
            SetViewBag();
            return View();
        }

        public void SetViewBag(long? selectedId = null)
        {
            var dao = new CategoryDAO();
            ViewBag.CategoryID = new SelectList(dao.ListAll(), "ID", "Name", selectedId);
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            try
            {
                new ContentDAO().Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SuperMarketK/Controllers/ContentController.cs
using Model.DAO;
using Model.EntityFramework;
using PusherServer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SuperMarketK.Controllers
{
    public class ContentController : Controller
    {

        SuperMarketKDbContext db = new SuperMarketKDbContext();
        // GET: Content
        public ActionResult Index()
        {
            var model = new ContentDAO();
            ViewBag.ListXemNhieu = model.getXemNhieu();
            return View(model.getList());
        }

        public ActionResult DetailNew(long id)
        {
            var model = new ContentDAO();
            model.tangView(id);
            ViewBag.ListXemNhieu = model.getXemNhieu();
            return View(model.GetByID(id));
        }

        public ActionResult Comments(long? id)
        {
            var comments = db.Comments.Where(x => x.PostID == id).ToArray();
            return Json(comments, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Comment(Comment data)
        {
            if (string.IsNullOrEmpty(data.Email) || string.IsNullOrEmpty(data.Message) || string.IsNullOrEmpty(data.Name))
            {
                return null;
            }
            data.CreatedDate = DateTime.Now;
            db.Comments.Add(data);
            db.SaveChanges();
            //var options = new PusherOptions();
            //options.Cluster = "ap1";
            //var pusher = new Pusher("1228143", "76aed70b9604a2cf8a17", "1f2d8d2b1b34485451e3", options);
            //ITriggerResult result = await pusher.TriggerAsync("asp_channel", "asp_event", data);
            return Content("ok");
        }

    }
}

SuperMarketK/Areas/Admin/Views/Content/Create.cshtml
@model Model.EntityFramework.Content

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="d-flex">
    <h2 class="p-2">MORE NEW NEWS</h2>
    <div class="ml-auto p-2">@Html.ActionLink("Back", "Index", null, new { @class = "btn btn-danger" })</div>
</div>

@using (Html.BeginForm("Create", "Content", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">General information</h6>
        </div>
        <div class="card-body">
            <div class="container d-flex justify-content-center">
                <div class="form-horizontal col-md-10">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control border-left-primary border-left-primary" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Description, 5, 40, new { @class = "form-control border-left-primary" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-5">Details</label>
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Detail, 5, 40, new { @class = "form-control border-left-primary", @id = "txtDetail" })
                            @Html.ValidationMessageFor(model => model.Detail, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CategoryID, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.CategoryID, null, new { @class = "form-control border-left-primary" })
                            @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-5">Chose Image</label>
                        <div class="col-md-10">
                            <input type="file" name="ImageFile" required/>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-12">
                            <input type="submit" value="Create" class="btn btn-success" style="width:30%" />
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
}
<script>
    CKEDITOR.replace("txtDetail");
</script>

SuperMarketK/Areas/Admin/Views/Content/Details.cshtml
@model Model.EntityFramework.Content
@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<style>
    dt {
        margin: 3px 0px;
    }
</style>
<div class="d-flex">
    <h3 class="mr-auto p-2">THÔNG TIN TIN TỨC</h3>
    <div class="p-2">@Html.ActionLink("Sửa thông tin", "Edit", new { id = Model.ID }, new { @class = "btn btn-success" })</div>
    <div class="p-2">@Html.ActionLink("Back", "Index", null, new { @class = "btn btn-danger" })</div>
</div>
<div>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">General Information</h6>
        </div>
        <div class="card-body">
            <div class="container d-flex justify-content-center">
                <div class="form-horizontal col-md-10">
                        <dl>
                            <dt>
                                @Html.DisplayNameFor(model => model.Name)
                            </dt>

                            <dd>
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control border-left-primary" })
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Description)
                            </dt>

                            <dd>
                                @Html.TextAreaFor(model => model.Description,5,40, new { @class = "form-control border-left-primary" })
                            </dd>

                            <dt>
                                Hình Ảnh
                            </dt>

                            <dd>
                                @Html.TextBoxFor(model => model.Image, new { @class = "form-control border-left-primary" })
                            </dd>                           
                        </dl>
                    </div>
                
            </div>
        </div>
    </div>

</div>

SuperMarketK/Areas/Admin/Views/Content/Edit.cshtml
@model Model.EntityFramework.Content

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="d-flex">
    <h2 class="p-2">CHỈNH SỬA TIN TỨC</h2>
    <div class="ml-auto p-2">@Html.ActionLink("Back", "Index", null, new { @class = "btn btn-danger" })</div>
</div>

@using (Html.BeginForm("Edit", "Content", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">General Information</h6>
        </div>
        <div class="card-body">
            <div class="container d-flex justify-content-center">
                <div class="form-horizontal col-md-10">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control border-left-primary border-left-primary" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Description, 5, 40, new { @class = "form-control border-left-primary" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-5">Nội dung chi tiết</label>
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Detail, 5, 40, new { @class = "form-control border-left-primary", @id = "txtDetail" })
                            @Html.ValidationMessageFor(model => model.Detail, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CategoryID, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.CategoryID, null, new { @class = "form-control border-left-primary" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-5">Choose image</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control border-left-primary border-left-primary" value="@Model.Image" />
                            <input type="file" name="ImageFile" style="margin-top: 10px" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-12">
                            <input type="submit" value="Save" class="btn btn-success" style="width:30%" />
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
}

<script>
    CKEDITOR.replace("txtDetail");
</script>

SuperMarketK/Areas/Admin/Views/Content/Index.cshtml
@model PagedList.IPagedList<Model.EntityFramework.Content>
@using PagedList.Mvc
@{
    ViewBag.Title = "Tin tức";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    string statusDelete = ViewBag.GroupID == "ADMIN" ? "enable" : "disabled";
}
@section jsFooter{
    <script src="~/Assets/js/sb-admin-2.js"></script>
}

<div class="d-flex">
    <h2 class="mr-auto p-2">LIST OF NEWS</h2>
    <div class="p-2">@Html.ActionLink("Create new", "Create", null, new { @class = "btn btn-success" })</div>
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">News Board</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" width="100%" cellspacing="0">
                <thead class="thead-light">
                    <tr>
                        <th>
                            ID
                        </th>
                        <th>
                            News name
                        </th>
                        <th>
                            Description
                        </th>
                        <th width="15%">
                            Date created
                        </th>
                        <th width="15%">
                            Create by
                        </th>
                        <th width="10%">Action</th>
                    </tr>
                </thead>

                @foreach (var item in Model)
                {
                    <tr id="row_@item.ID">
                        <td>
                            @Html.DisplayFor(modelItem => item.ID)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td width="40%">
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @item.CreatedDate.Value.ToString("dd/MM/yyyy")
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CreatedBy)
                        </td>
                        <td style="text-align: center">
                            @Html.ActionLink(" ", "Edit", new { id = item.ID }, new { @style = "color: #28a745", @class = "btnEdit" })
                            @Html.ActionLink(" ", "Details", new { id = item.ID }, new { @class = "btnDetail ml-1 mr-1" })
                            @Ajax.ActionLink(" ", "Delete", new { id = item.ID }, new AjaxOptions
                       {
                           Confirm = "Bạn có muốn xóa bản ghi này?",
                           OnComplete = "$('#row_" + @item.ID + "').remove()",
                           HttpMethod = "Delete",
                       }, new { @style = "color: #dc3545", @class = @statusDelete + " btnDelete" })
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>

<div class="d-flex flex-row-reverse">

    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, @keyword = @ViewBag.keyword }))

</div>
<script>$(".btnEdit").prepend("<i class='fa-solid fa-pen-to-square'></i> ");</script>
<script>$(".btnDetail").prepend("<i class='fa-solid fa-eye'></i> ");</script>
<script>$(".btnDelete").prepend("<i class='fa-solid fa-trash'></i> ");</script>