SuperMarketK/Areas/Admin/Controllers/SlideController.cs
using Model.DAO;
using Model.EntityFramework;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SuperMarketK.Areas.Admin.Controllers
{
    public class SlideController : BaseController
    {
        SuperMarketKDbContext db = new SuperMarketKDbContext();
        // GET: Admin/Slide
        public ActionResult Index(string keyword, int page = 1, int pageSize = 10)
        {
            var dao = new SlideDAO();
            var model = dao.ListAllPaging(keyword, page, pageSize);
            var userLogin = (SuperMarketK.Common.UserLogin)Session["USER_SESSION"];
            ViewBag.GroupID = userLogin.GroupID;
            ViewBag.keyword = keyword;
            return View(model);
        }
        

        // GET: Admin/Slide/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slide slide = db.Slides.Find(id);
            if (slide == null)
            {
                return HttpNotFound();
            }
            return View(slide);
        }
        
        // GET: Admin/Slide/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Slide/Create
        [HttpPost]
        public ActionResult Create(Slide slide, HttpPostedFileBase ImageFile)
        {
            if (ModelState.IsValid)
            {
                string fileName = null;
                if (ImageFile != null && ImageFile.ContentLength > 0)
                {
                    // extract only the fielname
                    fileName = Path.GetFileName(ImageFile.FileName);
                    // store the file inside ~/Assets/client/images folder
                    var path = Path.Combine(Server.MapPath("~/Assets/client/images"), fileName);
                    ImageFile.SaveAs(path);
                }
                slide.CreatedDate = DateTime.Now;
                var userLogin = (SuperMarketK.Common.UserLogin)Session["USER_SESSION"];
                slide.CreatedBy = userLogin.UserName;
                slide.Status = true;
                slide.Image = "/Assets/client/images/" + fileName;
                db.Slides.Add(slide);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(slide);
        }

        // GET: Admin/Slide/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slide slide = db.Slides.Find(id);
            if (slide == null)
            {
                return HttpNotFound();
            }
            SetViewBag();
            return View(slide);
        }

        // POST: Admin/Slide/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Image,DisplayOrder,Link,Description,CreatedDate,CreatedBy,ModifiedDate,ModifiedBy,Status")] Slide slide, HttpPostedFileBase ImageFile = null)
        {
            if (ModelState.IsValid)
            {
                string fileName = null;
                var sp = db.Slides.Find(slide.ID);
                if (ImageFile != null && ImageFile.ContentLength > 0)
                {
                    // extract only the fielname
                    fileName = Path.GetFileName(ImageFile.FileName);
                    // store the file inside ~/Assets/client/images folder
                    var path = Path.Combine(Server.MapPath("~/Assets/client/images"), fileName);
                    ImageFile.SaveAs(path);
                    sp.Image = "/Assets/client/images/" + fileName;
                }
                sp.DisplayOrder = slide.DisplayOrder;
                sp.Link = slide.Link;
                sp.Description = slide.Description;
                sp.Status = slide.Status;
                if (ImageFile == null)
                {
                    slide.Image = sp.Image;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(slide);
        }

        // POST: Admin/Product/Delete/5
        [HttpDelete]
        public ActionResult Delete(long id)
        {
            Slide slide = db.Slides.Find(id);
            db.Slides.Remove(slide);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public void SetViewBag(string selectID = null)
        {
            var listStatusSelected = new List<SelectListItem>
                {
                    new SelectListItem { Text = "Kích hoạt", Value = "true", Selected = true },
                    new SelectListItem { Text = "Vô hiệu hóa", Value = "false" },
                };
            ViewBag.listStatusSelected = listStatusSelected;
        }
    }
}

SuperMarketK/Areas/Admin/Views/Slide/Create.cshtml
@model Model.EntityFramework.Slide

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="d-flex">
    <h2 class="p-2">CREATE NEW SLIDE</h2>
    <div class="ml-auto p-2">@Html.ActionLink("Back", "Index", null, new { @class = "btn btn-danger" })</div>
</div>
@using (Html.BeginForm("Create", "Slide", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">General Information</h6>
        </div>
        <div class="card-body">
            <div class="container d-flex justify-content-center">
                <div class="form-horizontal col-md-10">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <label class="control-label col-md-5">Choose image</label>
                        <div class="col-md-10">
                            <input type="file" accept=".jpg, .png, .jpeg, .gif, .bmp, .tif, .tiff|image/*" name="ImageFile" required />
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Description, 5, 40, new { @class = "form-control border-left-primary" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DisplayOrder, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DisplayOrder, new { htmlAttributes = new { @class = "form-control border-left-primary border-left-primary" } })
                            @Html.ValidationMessageFor(model => model.DisplayOrder, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Link, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Link, new { htmlAttributes = new { @class = "form-control border-left-primary border-left-primary" } })
                            @Html.ValidationMessageFor(model => model.Link, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-12">
                            <input type="submit" value="Create" class="btn btn-success" style="width:30%" />
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
}

SuperMarketK/Areas/Admin/Views/Slide/Details.cshtml
@model Model.EntityFramework.Slide
@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<style>
    dt {
        margin: 3px 0px;
    }
</style>
<div class="d-flex">
    <h3 class="mr-auto p-2">THÔNG TIN SLIDE</h3>
    <div class="p-2">@Html.ActionLink("Sửa thông tin", "Edit", new { id = Model.ID }, new { @class = "btn btn-success" })</div>
    <div class="p-2">@Html.ActionLink("Back", "Index", null, new { @class = "btn btn-danger" })</div>
</div>
<div>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">General Information</h6>
        </div>
        <div class="card-body">
            <div class="container d-flex justify-content-center">
                <div class="form-horizontal col-md-10">
                    <dl>
                        <dt>
                            @Html.DisplayNameFor(model => model.Description)
                        </dt>

                        <dd>
                            @Html.TextBoxFor(model => model.Description, new { @class = "form-control border-left-primary" })
                        </dd>


                        <dt>
                            @Html.DisplayNameFor(model => model.DisplayOrder)
                        </dt>

                        <dd>
                            @Html.TextBoxFor(model => model.DisplayOrder, new { @class = "form-control border-left-primary" })
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.CreatedDate)
                        </dt>

                        <dd>
                            @Html.TextBoxFor(model => model.CreatedDate, new { @class = "form-control border-left-primary" })
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.CreatedBy)
                        </dt>

                        <dd>
                            @Html.TextBoxFor(model => model.CreatedBy, new { @class = "form-control border-left-primary" })
                        </dd>

                        <dt>
                            Hình Ảnh
                        </dt>

                        <dd>
                            <img src="@Model.Image" alt="@Model.Status" class="img-thumbnail">
                            @*@Html.TextBoxFor(model => model.Image, new { @class = "form-control border-left-primary" })*@
                        </dd>
                    </dl>
                </div>

            </div>
        </div>
    </div>

</div>

SuperMarketK/Areas/Admin/Views/Slide/Edit.cshtml
@model Model.EntityFramework.Slide

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="d-flex">
    <h2 class="p-2">CHỈNH SỬA SLIDE</h2>
    <div class="ml-auto p-2">@Html.ActionLink("Back", "Index", null, new { @class = "btn btn-danger" })</div>
</div>
@using (Html.BeginForm("Edit", "Slide", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">General Information</h6>
        </div>
        <div class="card-body">
            <div class="container d-flex justify-content-center">
                <div class="form-horizontal col-md-10">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Description, 5, 40, new { @class = "form-control border-left-primary" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DisplayOrder, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DisplayOrder, new { htmlAttributes = new { @class = "form-control border-left-primary border-left-primary" } })
                            @Html.ValidationMessageFor(model => model.DisplayOrder, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Link, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Link, new { htmlAttributes = new { @class = "form-control border-left-primary border-left-primary" } })
                            @Html.ValidationMessageFor(model => model.Link, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-10">
                            @Html.DropDownList("Status", (List<SelectListItem>)ViewBag.listStatusSelected, new { @class = "form-control border-left-primary" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-5">Choose image</label>
                        <div class="col-md-10">
                            <input type="file" name="ImageFile" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-12">
                            <input type="submit" value="Edit" class="btn btn-success" style="width:30%" />
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>


}

SuperMarketK/Areas/Admin/Views/Slide/Index.cshtml
@model PagedList.IPagedList<Model.EntityFramework.Slide>
@using PagedList.Mvc
@{
    ViewBag.Title = "Slide";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    string statusDelete = ViewBag.GroupID == "ADMIN" ? "enable" : "disabled";
}
@section jsFooter{
    <script src="~/Assets/js/sb-admin-2.js"></script>
}
<div class="d-flex">
    <h2 class="mr-auto p-2">SLIDE LIST</h2>
    <div class="p-2">@Html.ActionLink("Create new", "Create", null, new { @class = "btn btn-success" })</div>
</div>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Table Slide</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" width="100%" cellspacing="0">
                <tr>
                    <th>
                        ID
                    </th>
                    <th>
                        Image
                    </th>
                    <th>
                        Order of appearance
                    <th>
                        Url
                    </th>
                    <th>
                        Status
                    </th>
                    <th>
                        Created by
                    </th>
                    <th width="20%">Action</th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr id="row_@item.ID">
                        <td>
                            @Html.DisplayFor(modelItem => item.ID)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Image)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DisplayOrder)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Link)
                        </td>
                        <td>
                            @(item.Status == true ? "Đã kích hoạt" : "Vô hiệu hóa")
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CreatedBy)
                        </td>

                        <td style="text-align: center">
                            @Html.ActionLink(" ", "Edit", new { id = item.ID }, new { @style = "color: #28a745", @class = "btnEdit" })
                            @Html.ActionLink(" ", "Details", new { id = item.ID }, new { @class = "btnDetail ml-1 mr-1" })
                            @Ajax.ActionLink(" ", "Delete", new { id = item.ID }, new AjaxOptions
                       {
                           Confirm = "Bạn có muốn xóa bản ghi này?",
                           OnComplete = "$('#row_" + @item.ID + "').remove()",
                           HttpMethod = "Delete",
                       }, new { @style = "color: #dc3545", @class = @statusDelete + " btnDelete" })
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

<div class="d-flex flex-row-reverse">

    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, @keyword = @ViewBag.keyword }))

</div>
<script>$(".btnEdit").prepend("<i class='fa-solid fa-pen-to-square'></i> ");</script>
<script>$(".btnDetail").prepend("<i class='fa-solid fa-eye'></i> ");</script>
<script>$(".btnDelete").prepend("<i class='fa-solid fa-trash'></i> ");</script>